service:
    MAPPER:
        mapping-config: {}
        mapping-enabled: false
orchestration:
    MAPPER:
        mapping-config: {}
        mapping-enabled: true
    Sl-Or:
        virtualizer_type: GLOBAL
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: false
    MANAGERS:
    - STATIC
    STATIC:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: STATIC-NFFG
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: NFFGBasedStaticFileAdapter
                path: examples/sapalias-antiaff-delegable-net2.nffg
                log_dir: log/
                check_backward_links: true
