service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or:
        virtualizer_type: SINGLE
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: true
    MANAGERS:
    - Docker2
    - SDN2
    Docker2:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: Docker2
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /
                url: http://192.168.0.123:8888
    SDN2:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: SDN2
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /ro/sdn
                url: http://192.168.0.18:8899
