service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or:
        virtualizer_type: SINGLE
    ESCAPE-SERVICE:
        virtualizer_type: SINGLE
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: true
    MANAGERS:
    - MININET
    - OPENSTACK
    - RYU
    - DOCKER-1
    MININET:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: MININET
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/mininet
                url: http://dummy:8899
    OPENSTACK:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: OPENSTACK
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/os
                url: http://dummy:8899
                timeout: 1
                features:
                    antiaffinity: true
    DOCKER-1:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: DOCKER-1
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/docker1
                url: http://dummy:8899
    UN:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: UN
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/un
                url: http://dummy:8899
    RYU:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: RYU
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/ryu
                url: http://dummy:8899
