service:
    MAPPER:
        mapping-config: {}
        mapping-enabled: false
orchestration:
    MAPPER:
        mapping-config: {}
        mapping-enabled: true
    Sl-Or:
        virtualizer_type: SINGLE
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: false
    MANAGERS:
    - STATIC
    STATIC:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: STATIC
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: unify-get-config.xml
                log_dir: log/
