orchestration:
    Sl-Or:
        virtualizer_type: GLOBAL
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: false
    MANAGERS:
    - SSSA
    SSSA:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: SSSA
        diff: true
        poll: false
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: escape
                url: http://127.0.0.1:8899
